from __future__ import annotations

import csv
import json
import os
import shutil
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

from .config import load_yaml
from .logs.schema import HEVC_STYLE_COLUMNS, PERCENT_COLUMNS
from .quality import resolve_quality
from .utils import ensure_dir, expected_yuv420_size, read_json, require_file, run_logged, write_json


def discover_input_metadata(input_yuv: Path, explicit_metadata: Path | None = None) -> dict[str, Any]:
    if explicit_metadata is not None:
        return read_json(explicit_metadata)
    candidates = [
        input_yuv.parent.parent / "metadata.json",
        input_yuv.parent / "metadata.json",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return read_json(candidate)
    raise FileNotFoundError(
        "Could not find input metadata. Pass --input-metadata or use a YUV generated by prepare-yuv."
    )


def _input_props(metadata: dict[str, Any]) -> tuple[int, int, int, int]:
    inp = metadata["input"]
    return int(inp["encoded_width"]), int(inp["encoded_height"]), int(inp["frames"]), int(inp.get("fps") or 30)


def _check_recon(recon: Path, width: int, height: int, frames: int) -> None:
    require_file(recon, "reconstructed YUV")
    actual = recon.stat().st_size
    expected = expected_yuv420_size(width, height, frames)
    if actual != expected:
        raise ValueError(f"Bad recon size for {recon}: actual={actual} expected={expected}")


def _format_x265_params(params: dict[str, Any], gop_size: int, b_frames: int) -> str:
    formatted: list[str] = []
    for key, value in params.items():
        if isinstance(value, str):
            value = value.format(gop_size=gop_size, b_frames=b_frames)
        formatted.append(f"{key}={value}")
    return ":".join(formatted)


def _decode_with_ffmpeg(ffmpeg: str, bitstream: Path, recon: Path, frames: int, log_path: Path) -> None:
    cmd = [
        ffmpeg,
        "-y",
        "-hide_banner",
        "-i",
        str(bitstream),
        "-frames:v",
        str(frames),
        "-pix_fmt",
        "yuv420p",
        "-f",
        "rawvideo",
        str(recon),
    ]
    run_logged(cmd, log_path)


def _export_frames(ffmpeg: str, recon: Path, output_dir: Path, log_dir: Path, metadata: dict[str, Any]) -> None:
    inp = metadata["input"]
    width, height, frames, fps = _input_props(metadata)
    source_names_path = Path(inp["source_names"])
    names = source_names_path.read_text(encoding="utf-8").splitlines()
    if len(names) != frames:
        raise ValueError(f"Source manifest length mismatch: {len(names)} != {frames}")

    tmp_dir = ensure_dir(output_dir / "_tmp_export")
    if tmp_dir.exists():
        shutil.rmtree(tmp_dir)
    ensure_dir(tmp_dir)
    cmd = [
        ffmpeg,
        "-y",
        "-hide_banner",
        "-loglevel",
        "error",
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p",
        "-s",
        f"{width}x{height}",
        "-r",
        str(fps),
        "-i",
        str(recon),
        "-frames:v",
        str(frames),
        str(tmp_dir / "%06d.jpg"),
    ]
    run_logged(cmd, log_dir / f"{output_dir.name}_frames.log")
    ensure_dir(output_dir)
    for idx, source_name in enumerate(names, start=1):
        tmp_frame = tmp_dir / f"{idx:06d}.jpg"
        if not tmp_frame.is_file():
            raise FileNotFoundError(f"Missing exported frame: {tmp_frame}")
        shutil.move(str(tmp_frame), str(output_dir / source_name))
    shutil.rmtree(tmp_dir)


def _fallback_frame_type(index: int, gop_size: int, b_frames: int) -> str:
    if index % gop_size == 0:
        return "I-SLICE"
    if b_frames <= 0:
        return "P-SLICE"
    return "P-SLICE" if index % (b_frames + 1) == 0 else "B-SLICE"


def _ffprobe_frames(ffprobe: str, bitstream: Path) -> list[dict[str, Any]]:
    cmd = [
        ffprobe,
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_entries",
        "frame=pict_type,pkt_size",
        "-of",
        "json",
        str(bitstream),
    ]
    try:
        proc = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
        data = json.loads(proc.stdout)
    except Exception:
        return []
    frames = data.get("frames", [])
    return frames if isinstance(frames, list) else []


def _write_normalized_csv(
    csv_path: Path,
    bitstream: Path,
    metadata: dict[str, Any],
    codec_cfg: dict[str, Any],
    qp: int,
    effective_value: int,
    ffprobe: str,
) -> None:
    width, height, frame_count, _fps = _input_props(metadata)
    _ = width, height
    prediction = codec_cfg.get("prediction", {})
    gop_size = int(prediction.get("gop_size", 32))
    b_frames = int(prediction.get("b_frames", 3))
    probed = _ffprobe_frames(ffprobe, bitstream)

    ensure_dir(csv_path.parent)
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=HEVC_STYLE_COLUMNS)
        writer.writeheader()
        for idx in range(frame_count):
            frame_info = probed[idx] if idx < len(probed) else {}
            pict = str(frame_info.get("pict_type") or "").upper()
            if pict == "I":
                frame_type = "I-SLICE"
            elif pict == "P":
                frame_type = "P-SLICE"
            elif pict == "B":
                frame_type = "B-SLICE"
            else:
                frame_type = _fallback_frame_type(idx, gop_size, b_frames)

            pkt_size = frame_info.get("pkt_size")
            try:
                bits = int(pkt_size) * 8
            except (TypeError, ValueError):
                bits = 0

            row: dict[str, Any] = {col: "" for col in HEVC_STYLE_COLUMNS}
            row.update(
                {
                    "Encode Order": idx,
                    "Type": frame_type,
                    "POC": idx % gop_size,
                    "QP": f"{float(effective_value):.2f}",
                    "Bits": bits,
                    "Scenecut": 0,
                    "Y PSNR": "",
                    "U PSNR": "",
                    "V PSNR": "",
                    "YUV PSNR": "",
                    "SSIM": "",
                    "SSIM(dB)": "",
                    "Latency": "",
                    "List 0": "-",
                    "List 1": "-",
                    "GOPPos": idx % gop_size,
                    "TemporalLayer": 0,
                }
            )
            if codec_cfg.get("logs", {}).get("dummy_missing_fields", True):
                for col in PERCENT_COLUMNS:
                    row[col] = "0.00%"
            writer.writerow(row)


def compress_one(
    input_yuv: Path,
    codec_config: Path,
    qp: int,
    output_dir: Path,
    input_metadata: Path | None = None,
    hmstyle_csv: bool | None = None,
) -> dict[str, Any]:
    codec_cfg = load_yaml(codec_config)
    metadata = discover_input_metadata(input_yuv, input_metadata)
    width, height, frames, fps = _input_props(metadata)
    codec = codec_cfg["codec"]
    runner = codec_cfg["runner"]
    quality_rule = codec_cfg.get("quality", {}).get("qp_mapping", "identity")
    quality = resolve_quality(qp, quality_rule)

    bitstream_dir = ensure_dir(output_dir / "bitstream")
    recon_dir = ensure_dir(output_dir / "recon")
    frames_dir = ensure_dir(output_dir / "frames")
    logs_dir = ensure_dir(output_dir / "logs")
    ensure_dir(output_dir / "input")
    shutil.copy2(input_yuv, output_dir / "input" / input_yuv.name)
    source_names = Path(metadata["input"]["source_names"])
    local_source_names = output_dir / "input" / "source_names.txt"
    if source_names.is_file():
        shutil.copy2(source_names, local_source_names)
        metadata = {
            **metadata,
            "input": {
                **metadata["input"],
                "source_names": str(local_source_names),
            },
        }

    ffmpeg = codec_cfg.get("tools", {}).get("ffmpeg") or os.environ.get("FFMPEG", "ffmpeg")
    ffprobe = codec_cfg.get("tools", {}).get("ffprobe") or os.environ.get("FFPROBE", "ffprobe")
    prediction = codec_cfg.get("prediction", {})
    gop_size = int(prediction.get("gop_size", 32))
    b_frames = int(prediction.get("b_frames", 3))

    if runner == "ffmpeg":
        bitstream, recon = _compress_ffmpeg(
            input_yuv, codec_cfg, codec, qp, quality.effective_value, width, height, frames, fps, gop_size, b_frames,
            bitstream_dir, recon_dir, logs_dir, ffmpeg,
        )
    elif runner == "hm":
        bitstream, recon = _compress_hm(
            input_yuv, codec_cfg, codec, qp, width, height, frames, fps, gop_size, bitstream_dir, recon_dir, logs_dir,
        )
    elif runner == "vtm":
        bitstream, recon = _compress_vtm(
            input_yuv, codec_cfg, codec, qp, width, height, frames, fps, bitstream_dir, recon_dir, logs_dir,
        )
    elif runner == "jm":
        bitstream, recon = _compress_jm(
            input_yuv, codec_cfg, codec, qp, width, height, frames, fps, gop_size, bitstream_dir, recon_dir, logs_dir,
        )
    else:
        raise ValueError(f"Unsupported runner: {runner}")

    _check_recon(recon, width, height, frames)
    _export_frames(ffmpeg, recon, frames_dir / bitstream.stem, logs_dir, metadata)
    normalized_csv = logs_dir / f"{codec}_qp{qp}_hmstyle.csv"
    write_hmstyle = codec_cfg.get("logs", {}).get("normalize_to_hevc_csv", True)
    if hmstyle_csv is not None:
        write_hmstyle = hmstyle_csv
    if write_hmstyle:
        _write_normalized_csv(normalized_csv, bitstream, metadata, codec_cfg, qp, quality.effective_value, ffprobe)

    result = {
        "input": metadata["input"],
        "codec": codec,
        "runner": runner,
        "codec_config": str(codec_config),
        "requested_qp": qp,
        "effective_quality": {
            "kind": quality.quality_param_kind,
            "value": quality.effective_value,
            "mapping_rule": quality.mapping_rule,
        },
        "bitstream": str(bitstream),
        "recon": str(recon),
        "frames": str(frames_dir / bitstream.stem),
        "logs": str(logs_dir),
        "normalized_csv": str(normalized_csv) if normalized_csv.exists() else None,
    }
    write_json(output_dir / "metadata.json", result)
    return result


def _compress_ffmpeg(
    input_yuv: Path,
    cfg: dict[str, Any],
    codec: str,
    requested_qp: int,
    effective_value: int,
    width: int,
    height: int,
    frames: int,
    fps: int,
    gop_size: int,
    b_frames: int,
    bitstream_dir: Path,
    recon_dir: Path,
    logs_dir: Path,
    ffmpeg: str,
) -> tuple[Path, Path]:
    encoder = cfg["encoder"]
    ext = ".mp4"
    suffix = f"qp{effective_value}"
    cmd = [
        ffmpeg,
        "-y",
        "-hide_banner",
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p",
        "-s",
        f"{width}x{height}",
        "-r",
        str(fps),
        "-i",
        str(input_yuv),
        "-frames:v",
        str(frames),
        "-c:v",
        encoder,
    ]
    if encoder == "libx264":
        cmd += ["-g", str(gop_size), "-keyint_min", str(gop_size), "-sc_threshold", "0", "-bf", str(b_frames), "-qp", str(effective_value)]
    elif encoder == "libx265":
        params = _format_x265_params(cfg.get("x265", {}).get("params", {}), gop_size, b_frames)
        cmd += ["-x265-params", params, "-qp", str(effective_value)]
    elif encoder == "libsvtav1":
        ext = ".mkv"
        suffix = f"qp{requested_qp}_q{effective_value}"
        cmd += ["-g", str(gop_size), "-keyint_min", str(gop_size), "-sc_threshold", "0", "-bf", str(b_frames), "-qp", str(effective_value)]
        if cfg.get("ffmpeg", {}).get("preset") is not None:
            cmd += ["-preset", str(cfg["ffmpeg"]["preset"])]
    elif encoder == "libvpx-vp9":
        ext = ".webm"
        suffix = f"qp{requested_qp}_crf{effective_value}"
        ffmpeg_cfg = cfg.get("ffmpeg", {})
        cmd += ["-g", str(gop_size), "-keyint_min", str(gop_size), "-crf", str(effective_value), "-b:v", "0"]
        if ffmpeg_cfg.get("row_mt", False):
            cmd += ["-row-mt", "1"]
        if ffmpeg_cfg.get("tile_columns") is not None:
            cmd += ["-tile-columns", str(ffmpeg_cfg["tile_columns"])]
        if ffmpeg_cfg.get("quality") is not None:
            cmd += ["-quality", str(ffmpeg_cfg["quality"])]
        if ffmpeg_cfg.get("cpu_used") is not None:
            cmd += ["-cpu-used", str(ffmpeg_cfg["cpu_used"])]
    else:
        raise ValueError(f"Unsupported FFmpeg encoder: {encoder}")

    threads = cfg.get("ffmpeg", {}).get("threads")
    if threads is not None:
        cmd += ["-threads", str(threads)]
    cmd += [*map(str, cfg.get("ffmpeg", {}).get("extra_args", []))]

    bitstream = bitstream_dir / f"{codec}_{suffix}{ext}"
    recon = recon_dir / f"{codec}_{suffix}.yuv"
    cmd += ["-an", str(bitstream)]
    run_logged(cmd, logs_dir / f"{codec}_encode.log")
    _decode_with_ffmpeg(ffmpeg, bitstream, recon, frames, logs_dir / f"{codec}_decode.log")
    return bitstream, recon


def _compress_hm(
    input_yuv: Path,
    cfg: dict[str, Any],
    codec: str,
    qp: int,
    width: int,
    height: int,
    frames: int,
    fps: int,
    gop_size: int,
    bitstream_dir: Path,
    recon_dir: Path,
    logs_dir: Path,
) -> tuple[Path, Path]:
    hm_cfg = cfg.get("hm", {})
    encoder = Path(hm_cfg.get("encoder_path") or "")
    base_cfg = Path(hm_cfg.get("cfg_path") or "")
    require_file(encoder, "HM encoder")
    require_file(base_cfg, "HM cfg")
    bitstream = bitstream_dir / f"{codec}_qp{qp}.bin"
    recon = recon_dir / f"{codec}_qp{qp}.yuv"
    cmd = [
        str(encoder),
        "-c",
        str(base_cfg),
        "-i",
        str(input_yuv),
        "-b",
        str(bitstream),
        "-o",
        str(recon),
        "-wdt",
        str(width),
        "-hgt",
        str(height),
        "-fr",
        str(fps),
        "-f",
        str(frames),
        "-q",
        str(qp),
        "--IntraPeriod=%s" % gop_size,
        "--InputBitDepth=%s" % hm_cfg.get("input_bit_depth", 8),
        "--InternalBitDepth=%s" % hm_cfg.get("internal_bit_depth", 8),
        "--InputChromaFormat=%s" % hm_cfg.get("input_chroma_format", 420),
        "--Profile=%s" % hm_cfg.get("profile", "main"),
        "--ConformanceWindowMode=%s" % hm_cfg.get("conformance_window_mode", 1),
    ]
    if hm_cfg.get("intra_qp_offset") is not None:
        cmd.append("--IntraQPOffset=%s" % hm_cfg["intra_qp_offset"])
    cmd += [*map(str, hm_cfg.get("extra_args", []))]
    run_logged(cmd, logs_dir / f"{codec}_encode.log")
    return bitstream, recon


def _compress_vtm(
    input_yuv: Path,
    cfg: dict[str, Any],
    codec: str,
    qp: int,
    width: int,
    height: int,
    frames: int,
    fps: int,
    bitstream_dir: Path,
    recon_dir: Path,
    logs_dir: Path,
) -> tuple[Path, Path]:
    vtm_cfg = cfg.get("vtm", {})
    encoder = Path(vtm_cfg.get("encoder_path") or "")
    base_cfg = Path(vtm_cfg.get("cfg_path") or "")
    require_file(encoder, "VTM encoder")
    require_file(base_cfg, "VTM cfg")
    bitstream = bitstream_dir / f"{codec}_qp{qp}.bin"
    recon = recon_dir / f"{codec}_qp{qp}.yuv"
    cmd = [
        str(encoder),
        "-c",
        str(base_cfg),
        "-i",
        str(input_yuv),
        "-b",
        str(bitstream),
        "-o",
        str(recon),
        "-wdt",
        str(width),
        "-hgt",
        str(height),
        "-fr",
        str(fps),
        "-f",
        str(frames),
        "-q",
        str(qp),
        "--InputBitDepth=%s" % vtm_cfg.get("input_bit_depth", 8),
        "--InternalBitDepth=%s" % vtm_cfg.get("internal_bit_depth", 8),
        "--OutputBitDepth=%s" % vtm_cfg.get("output_bit_depth", 8),
        "--InputChromaFormat=%s" % vtm_cfg.get("input_chroma_format", 420),
    ]
    cmd += [*map(str, vtm_cfg.get("extra_args", []))]
    run_logged(cmd, logs_dir / f"{codec}_encode.log")
    return bitstream, recon


def _compress_jm(
    input_yuv: Path,
    cfg: dict[str, Any],
    codec: str,
    qp: int,
    width: int,
    height: int,
    frames: int,
    fps: int,
    gop_size: int,
    bitstream_dir: Path,
    recon_dir: Path,
    logs_dir: Path,
) -> tuple[Path, Path]:
    jm_cfg = cfg.get("jm", {})
    encoder = Path(jm_cfg.get("encoder_path") or "")
    workdir = Path(jm_cfg.get("workdir") or encoder.parent)
    require_file(encoder, "JM encoder")
    bitstream = bitstream_dir / f"{codec}_qp{qp}.264"
    recon = recon_dir / f"{codec}_qp{qp}.yuv"
    generated_cfg = logs_dir / f"{codec}_qp{qp}.cfg"
    generated_cfg.write_text(
        "\n".join(
            [
                f'InputFile             = "{input_yuv}"',
                f"SourceWidth           = {width}",
                f"SourceHeight          = {height}",
                f"FrameRate             = {fps}",
                f"FramesToBeEncoded     = {frames}",
                f"IntraPeriod           = {gop_size}",
                "FrameSkip             = 0",
                f"LevelIdc              = {jm_cfg.get('level_idc', 51)}",
                f"QPISlice              = {qp}",
                f"QPPSlice              = {qp}",
                f"QPBSlice              = {qp}",
                f'OutputFile            = "{bitstream}"',
                f'ReconFile             = "{recon}"',
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    cmd = [str(encoder), "-f", str(generated_cfg), *map(str, jm_cfg.get("extra_args", []))]
    run_logged(cmd, logs_dir / f"{codec}_encode.log", cwd=workdir)
    return bitstream, recon


def compress_suite(
    input_yuv: Path,
    codec_configs: list[Path],
    qp: int,
    output_dir: Path,
    workers: int,
    input_metadata: Path | None = None,
    hmstyle_csv: bool | None = None,
) -> list[dict[str, Any]]:
    ensure_dir(output_dir)

    def run_one(codec_config: Path) -> dict[str, Any]:
        codec_cfg = load_yaml(codec_config)
        codec_out = output_dir / codec_cfg["codec"]
        return compress_one(input_yuv, codec_config, qp, codec_out, input_metadata, hmstyle_csv)

    results: list[dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=max(1, workers)) as pool:
        futures = {pool.submit(run_one, path): path for path in codec_configs}
        for future in as_completed(futures):
            results.append(future.result())
    write_json(output_dir / "metadata.json", {"runs": results, "workers": workers})
    return results
